export enum IconName {
  NodeJS = "nodejs.svg",
  MySql = "mysql.svg",
  PostgreSQL = "postgresql.svg",
  MongoDB = "mongodb.svg",
  ReactJS = "react.svg",
  ExpressJS = "expressjs_dark.svg",
  NestJS = "nestjs.svg",
  Bootstrap = "bootstrap.svg",
  MaterialUI = "materialui.svg",
  TailwindCSS = "tailwindcss.svg",
  ReactQuery = "reactquery.svg",
  Redux = "redux.svg",
  Typescript = "typescript.svg",
  PrismaJS = "prisma_dark.svg",
  NextJS = "nextjs_icon_dark.svg",
  ChakraUI = "chakra-ui.svg",
  FramerMotion = "framer_dark.svg",
}
